In [64]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.utils import data

# For data preprocess
import numpy as np
import csv
import os

# For plotting
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from utils.mylib import *
from d2l import torch as d2l

In [65]:
class MF(nn.Module):
    def __init__(self, n_users=1050, m_items=2050, n_factors=20):
        super(MF, self).__init__()

        self.U = torch.nn.Parameter(torch.ones(2, 2, requires_grad=True))
        self.V = torch.nn.Parameter(torch.ones(2, 2, requires_grad=True))

    
    def forward(self):
        # return torch.einsum('ij, ij -> i', [self.U[user], self.P[item] + self.net(self.P[item])])
        return (self.U * self.V).sum()




In [66]:
model = MF()

In [67]:
for _ in model.parameters():
    print(_)

Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [68]:
model.U.requires_grad_(False)

Parameter containing:
tensor([[1., 1.],
        [1., 1.]])

In [69]:
model.U.requires_grad

False

In [70]:
model.V.requires_grad

True

In [71]:
opt = torch.optim.SGD(filter(lambda p: p.requires_grad, model.parameters()), lr=0.1)

In [72]:
y = model()

In [73]:
y.backward()

In [74]:
opt.step()

In [75]:
model.V

Parameter containing:
tensor([[0.9000, 0.9000],
        [0.9000, 0.9000]], requires_grad=True)

In [76]:
model.U

Parameter containing:
tensor([[1., 1.],
        [1., 1.]])

In [77]:
model.U.requires_grad_(True)

Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [79]:
y = model()

In [80]:
y

tensor(3.6000, grad_fn=<SumBackward0>)

In [81]:
y.backward()

In [82]:
opt.step()

In [83]:
model.U

Parameter containing:
tensor([[0.9100, 0.9100],
        [0.9100, 0.9100]], requires_grad=True)

In [84]:
model.V

Parameter containing:
tensor([[0.7000, 0.7000],
        [0.7000, 0.7000]], requires_grad=True)

In [78]:

opt.add_param_group({'params': model.U})
opt.zero_grad()

In [60]:
model.V

Parameter containing:
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]], requires_grad=True)

In [62]:
opt.step()

In [63]:
model.U

Parameter containing:
tensor([[0.9100, 0.9100],
        [0.9100, 0.9100]], requires_grad=True)